[package]
name = "tagoto"
version = "0.1.0"
authors = ["Kiwifuit <75169058+Kiwifuit@users.noreply.github.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "tagoto"
harness = false # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"

[dependencies]
log = "0.4"
esp-idf-svc = { version = "0.52.1", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
# Remove `generic-queue-8` if you plan to use `embassy-time` WITH `embassy-executor`
embassy-time = { version = "0.5", features = ["generic-queue-8"] }
anyhow = "1.0.104"
embedded-hal = "1.0.0"
esp32-nimble = "0.12.0"
pms7003-rs = { git = "ssh://git@github.com/PjSWhite/pms7003-rs.git", ref = "40f652b", features = ["embedded-impl"] }
zerocopy = "0.8.56"

[build-dependencies]
embuild = "0.33"
